#!/usr/bin/env python3
"""Apply a partial key to the published Charles I / Nicholas cipher extracts.

This is a transparent decoder and audit generator, NOT an autonomous discovery
program and NOT independent authentication of the historical plaintext.
No desired plaintext is loaded when decoding. No source letter is repaired.
Run with --mode core to test only the compact periodic-alphabet hypothesis.
"""
from __future__ import annotations
import argparse
from collections import Counter
import csv
import hashlib
import json
from pathlib import Path
import re
from typing import Any

ROOT=Path(__file__).resolve().parent
KEY=json.loads((ROOT/'partial_key.json').read_text(encoding='utf-8'))
SOURCES=json.loads((ROOT/'input'/'sources.json').read_text(encoding='utf-8'))
PATTERN=re.compile(r'(?<!\d)\d{1,3}(?!\d)|[△中□+＋]')
MODES=('core','working','exploratory')


def core_letter(n: int) -> str | None:
    """The entire main alphabet is generated by this position-independent rule."""
    c=KEY['core']
    if c['minimum'] <= n <= c['maximum']:
        return c['row'][(n-c['minimum']) % c['period']].upper()
    return None


def value_for(n: int, mode: str='working') -> tuple[str,str,str]:
    """Return (output, category, basis). Empty output explicitly denotes a null."""
    if mode not in MODES:
        raise ValueError(f'Unknown mode: {mode}')
    letter=core_letter(n)
    if letter is not None:
        return letter,'periodic_letter','Fixed 24-position rule, restricted to 20–115.'
    if mode == 'core':
        return f'⟦{n}⟧','unresolved_numeric','Not covered by the core rule.'
    s=str(n)
    if s in KEY['additional_letters']:
        entry=KEY['additional_letters'][s]
        return entry['output'].upper(),'additional_letter',entry['evidence']
    if s in KEY['working_word_codes']:
        entry=KEY['working_word_codes'][s]
        return entry['output'].upper(),'working_word_code',entry['evidence']
    if mode == 'exploratory':
        if s in KEY['tentative_letters']:
            entry=KEY['tentative_letters'][s]
            return entry['output'].upper(),'tentative_letter',entry['evidence']
        if s in KEY['word_code_hypotheses']:
            entry=KEY['word_code_hypotheses'][s]
            if entry['output']:
                return entry['output'].upper(),'word_code_hypothesis',entry['evidence']
    # Exploratory hypotheses can compete with a proposed null (currently 376).
    if n in KEY['proposed_nulls']:
        return '','proposed_null',KEY['null_caveat']
    return f'⟦{n}⟧','unresolved_numeric','No adopted value; do not fill from narrative expectations.'


def audit_text(text: str, document: str='', mode: str='working') -> list[dict[str,Any]]:
    if mode not in MODES:
        raise ValueError(f'Unknown mode: {mode}')
    result=[]
    for occurrence,m in enumerate(PATTERN.finditer(text),1):
        raw=m.group()
        field_start=m.start()
        while field_start>0 and not text[field_start-1].isspace(): field_start-=1
        field_end=m.end()
        while field_end<len(text) and not text[field_end].isspace(): field_end+=1
        source_field=text[field_start:field_end]
        if raw.isdigit():
            n=int(raw)
            if source_field in KEY['dates']:
                out,category,basis=raw,'date_or_annotation','Literal date/annotation field; not removed as a null.'
            else:
                out,category,basis=value_for(n,mode)
        else:
            n=None
            out,category,basis=raw,'unresolved_graphic',KEY['graphics']
            if mode != 'core' and raw in KEY['working_graphic_codes']:
                entry=KEY['working_graphic_codes'][raw]
                out=entry['output'].upper()
                category,basis='working_graphic_code',entry['evidence']
                for gloss in KEY['inline_graphic_glosses']:
                    if gloss['symbol'] != raw:
                        continue
                    start=m.start()-gloss['source'].index(raw)
                    if start>=0 and text[start:start+len(gloss['source'])]==gloss['source']:
                        category='unresolved_graphic_role'
                        basis+=' Possible inline gloss; word value proposed, textual role unresolved.'
                        break
        result.append({
            'document':document,'occurrence':occurrence,'source_start':m.start(),
            'source_end':m.end(),'source_line':text.count('\n',0,m.start())+1,
            'raw':raw,'number':n,'source_field':source_field,
            'qualified_field':raw != source_field,'output':out,
            'category':category,'basis':basis,
            'left_context':text[max(0,m.start()-35):m.start()],
            'right_context':text[m.end():min(len(text),m.end()+35)]
        })
    return result


def render_value(record: dict[str,Any],hide_nulls: bool=False) -> str:
    category=record['category']
    if category=='proposed_null':
        return '' if hide_nulls else f'⟨∅:{record["raw"]}⟩'
    if category in ('tentative_letter','word_code_hypothesis'):
        return f'⟦{record["raw"]}:{record["output"]}?⟧'
    if category=='working_word_code':
        return '{'+record['output']+'}'
    if category=='working_graphic_code':
        return '{'+record['raw']+':'+record['output']+'}'
    if category=='unresolved_graphic_role':
        return f'⟦{record["raw"]}:{record["output"]};role?⟧'
    return record['output']


def decode(text: str, mode: str='working',hide_nulls: bool=False) -> str:
    pieces=[]
    previous=0
    for item in audit_text(text,mode=mode):
        pieces.append(text[previous:item['source_start']])
        pieces.append(render_value(item,hide_nulls))
        previous=item['source_end']
    pieces.append(text[previous:])
    return ''.join(pieces)


def compact(text: str,mode: str='working') -> str:
    """For disclosed passage checks only: remove spaces and word-code braces.

    Nulls are omitted under the proposed model. Original punctuation, stars,
    graphics and unresolved markers are NOT removed. U is NOT changed to V.
    """
    s=decode(text,mode=mode,hide_nulls=True)
    s=s.replace('{','').replace('}','')
    return re.sub(r'\s+','',s).upper()


def validate_sources() -> None:
    """Check the preserved extract hashes and their readable text copies."""
    for name,doc in SOURCES['documents'].items():
        text=doc['cipher_bearing_extract']
        if hashlib.sha256(text.encode('utf-8')).hexdigest()!=doc['extract_sha256']:
            raise ValueError(f'Source checksum failed: {name}')
        expected=text+'\n'+doc['plaintext_continuation']+'\n'
        path=ROOT/'input'/f'{name.lower()}.txt'
        if path.read_bytes()!=expected.encode('utf-8'):
            raise ValueError(f'Readable input differs from sources.json: {path.name}')


def document_output(doc: dict[str,Any], mode: str='working') -> str:
    """Render the same full document for audit and committed output files."""
    return (
        f'MODE: {mode}. Partial model; not a repaired or fully verified plaintext.\n'
        'Uppercase letters are model outputs; interspersed source prose is unchanged.\n'
        '⟨∅:n⟩ = proposed null; {WORD} = working code; ⟦n⟧ = unresolved; ⟦n:guess?⟧ = tentative.\n'
        '{sign:WORD} = working graphic; ⟦sign:WORD;role?⟧ = possible inline gloss, role unresolved.\n'
        'Original suffixes and graphics are preserved. All source date fields are retained.\n\n'
        +decode(doc['cipher_bearing_extract'],mode)
        +'\n\nUNCHANGED PLAINTEXT CONTINUATION:\n'+doc['plaintext_continuation']+'\n'
    )


def check_outputs() -> list[dict[str,Any]]:
    """Compare complete committed outputs with freshly decoded working text."""
    results=[]
    for name,doc in SOURCES['documents'].items():
        path=ROOT/'output'/f'{name.lower()}.txt'
        matches=path.is_file() and path.read_bytes()==document_output(doc).encode('utf-8')
        results.append({'document':name,'passed':matches})
    return results


def write_outputs() -> None:
    """Refresh the two committed working outputs after validating both inputs."""
    validate_sources()
    outputs={name:document_output(doc) for name,doc in SOURCES['documents'].items()}
    destination=ROOT/'output'
    destination.mkdir(parents=True,exist_ok=True)
    for name,text in outputs.items():
        (destination/f'{name.lower()}.txt').write_bytes(text.encode('utf-8'))


def check_proofs() -> list[dict[str,Any]]:
    proofs=json.loads((ROOT/'proof_passages.json').read_text(encoding='utf-8'))
    results=[]
    for p in proofs:
        text=SOURCES['documents'][p['document']]['cipher_bearing_extract']
        actual_source=text[p['source_start']:p['source_end']]
        if actual_source != p['source']:
            raise ValueError('Source offset mismatch in '+p['id'])
        actual=compact(actual_source,p['mode'])
        records=audit_text(actual_source,p['document'],p['mode'])
        results.append({**p,'actual':actual,'passed':actual==p['literal_compact_expected'],
                        'numeric_count':sum(r['number'] is not None for r in records),
                        'proposed_null_count':sum(r['category']=='proposed_null' for r in records),
                        'categories':dict(Counter(r['category'] for r in records))})
    return results


def create_audit(destination: Path) -> dict[str,Any]:
    validate_sources()
    destination.mkdir(parents=True,exist_ok=True)
    all_records=[]
    docs={}
    for name,doc in SOURCES['documents'].items():
        text=doc['cipher_bearing_extract']
        records=audit_text(text,name,'working')
        all_records.extend(records)
        docs[name]={'numeric_occurrences':sum(r['number'] is not None for r in records),
                    'graphics':sum(r['number'] is None for r in records),
                    'categories':dict(Counter(r['category'] for r in records))}
        for mode in MODES:
            (destination/f'{name.lower()}_{mode}_literal.txt').write_bytes(
                document_output(doc,mode).encode('utf-8'))
    core_values={r['number'] for r in all_records if r['category']=='periodic_letter'}
    proof_results=check_proofs()
    covered={}
    for name in SOURCES['documents']:
        positions=set()
        for p in proof_results:
            if p['document']==name:
                positions.update(range(p['source_start'],p['source_end']))
        covered[name]=sum(r['number'] is not None and r['source_start'] in positions for r in all_records if r['document']==name)
    result={
      'source_url':SOURCES['url'],
      'warning':'Mapping coverage is not decipherment accuracy. Passage tests check reproducibility against proposed readings, not an independent plaintext. Source errors and unknown code words remain.',
      'documents':docs,
      'combined':{'numeric_occurrences':sum(r['number'] is not None for r in all_records),
                  'graphic_occurrences':sum(r['number'] is None for r in all_records),
                  'categories':dict(Counter(r['category'] for r in all_records)),
                  'core_distinct_observed':len(core_values),
                  'core_predictions_unobserved':[n for n in range(20,116) if n not in core_values],
                  'proof_passages':len(proof_results),
                  'proofs_passed':sum(p['passed'] for p in proof_results),
                  'unique_numeric_occurrences_within_proof_passages':covered,
                  'unknown_numeric_values':dict(sorted(Counter(r['number'] for r in all_records if r['category']=='unresolved_numeric').items()))},
      'proof_results':proof_results,'tokens':all_records}
    (destination/'audit.json').write_text(json.dumps(result,indent=2,ensure_ascii=False),encoding='utf-8')
    fields=['document','occurrence','source_line','source_start','source_end','raw','source_field','qualified_field','output','category','basis','left_context','right_context']
    with (destination/'token_audit.csv').open('w',newline='',encoding='utf-8-sig') as f:
        writer=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore')
        writer.writeheader();writer.writerows(all_records)
    return result


def main() -> int:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--document',choices=['Charles','Nicholas','both'],default='both')
    parser.add_argument('--mode',choices=MODES,default='working')
    parser.add_argument('--hide-nulls',action='store_true',help='Omit model nulls for readability; no letter corrections are applied.')
    actions=parser.add_mutually_exclusive_group()
    actions.add_argument('--audit',type=Path,help='Generate all reading modes, token audit and passage checks in this directory.')
    actions.add_argument('--check',action='store_true',help='Check source integrity, disclosed passages and both committed working outputs.')
    actions.add_argument('--write-outputs',action='store_true',help='Refresh both files in output/ using the working key.')
    args=parser.parse_args()
    if (args.audit or args.check or args.write_outputs) and (
            args.document!='both' or args.mode!='working' or args.hide_nulls):
        parser.error('--document, --mode and --hide-nulls customize display only; omit them for file generation or checks.')
    try:
        validate_sources()
    except (OSError,ValueError) as error:
        parser.exit(1,f'Source validation failed: {error}\n')
    if args.audit:
        result=create_audit(args.audit)
        print(json.dumps(result['combined'],indent=2,ensure_ascii=False))
        return 0 if result['combined']['proofs_passed']==result['combined']['proof_passages'] else 1
    if args.check:
        results=check_proofs()
        print('PASS source hashes and readable input copies')
        for p in results:
            print(p['id'], 'PASS' if p['passed'] else 'FAIL',p['actual'])
        outputs=check_outputs()
        for item in outputs:
            print('PASS' if item['passed'] else 'FAIL',item['document'],'committed working output')
        if not all(item['passed'] for item in outputs):
            print('Review the key changes, then run --write-outputs to refresh output/.')
        return 0 if all(p['passed'] for p in results+outputs) else 1
    if args.write_outputs:
        write_outputs()
        print('Refreshed both working outputs in output/.')
        return 0
    for name,doc in SOURCES['documents'].items():
        if args.document not in (name,'both'): continue
        print(f'\n{name} — {args.mode} model, not a fully solved letter\n')
        print(decode(doc['cipher_bearing_extract'],args.mode,args.hide_nulls))
        print('\nUnchanged cleartext continuation:\n'+doc['plaintext_continuation'])
    return 0

if __name__=='__main__':
    raise SystemExit(main())
